name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: ðŸš€ Deploy on Server
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          if [ -z "$SSH_KEY" ]; then
            echo "âŒ SSH_KEY is empty" && exit 1
          fi
          echo "$SSH_KEY" | head -n 5
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
      - name: Run deploy script on server
        env:
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_USER: ${{ secrets.DEPLOY_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa ${SSH_USER}@${SSH_HOST} "bash /root/app/deploy.sh"
